### ISSUE TITLE
defaults overriding file settings

### ISSUE THREAD

**Issue by gnomff** [markround/tiller#14]
When I set a default value in defaults.yaml it is overriding the value set in the file config. Example:

defaults.yaml
```
global:  
  myval: 'default_value'  
```

common.yaml
```
data_sources:
  - defaults
  - file
  - environment_json
  - environment

template_sources:
  - file
```

production.yaml
```
myproperties.properties.erb:
  target: /my/path/myproperties.properties
  config:
    myval: 'override_value'
```

when I run tiller I get:
Warning, merging duplicate global and local values.
myval => 'override_value' being replaced by : 'default_value' from merged configuration

I am using v0.6.0
