### ISSUE TITLE
Same ERB template for all environments

### ISSUE THREAD

**Issue by humbargs** [markround/tiller#15]
How would I go about specifying a single erb template for all of my environments?  I currently have this in my common.yaml file:

```
---
exec: [ "/usr/bin/supervisord", "-n" ]
data_sources:
  - file
  - environment
  - defaults
template_sources:
  - file
defaults:
  global:
    some.properties.erb:
      user:   myuser
      group:  mygroup
      perms:  0644
      target: /usr/local/some.properties
```
When I run the above, I get this:
`Error : Could not load environment file /etc/tiller/environments/development.yaml`

The error message is correct, but I didn't want to have to specify that the template belongs to development environment when it belongs to all of my environments.  I was just looking for a way to specify the template globally so that it's automatically available to all of my environments.

**Comment by markround** [comment]
Hi,

Quick question - are you actually using multiple environments (each with a slightly different config/set of templates) and one common global template ? Or do you simply want to produce a parameterized container with a common set of templates wherever it runs ?

**Comment by markround** [comment]
I see one small issue with your config by the way - the template should not be under the global: block, that's for defining values across all your templates. You'd want to do something like :

```yaml
defaults:
  some.properties.erb:
    user:   myuser
    group:  mygroup
    perms:  0644
    target: /usr/local/some.properties
```
This might help. Although you'll still need to define at least one environment (either in the common.yaml, or in a separate environments/<env_name>.yaml file.
