### ISSUE TITLE
Using defaults and overide with environment plugin

### ISSUE THREAD

**Issue by jsedlace** [markround/tiller#16]
Hello Mark, 

I would like to use defaults plugin, some values defined in yaml file for each environment and have a possibility to override some settings with environments plugin. Is this somehow achievable?

**Comment by markround** [comment]
Sure. Assuming a templates/test.erb that looks like this:

```erb
Global value : <%= some_global_value %>
Local value : <%= some_local_value %>
Something from the environment : <%= env_some_var %>
```

And a common.yaml that looks like this:
```yaml
exec: ["/usr/bin/whatever"]
data_sources: [ 'defaults','file','environment' ]
template_sources: [ 'file' ]

defaults:
  global:
    some_global_value: "This is available to all environments"

environments:

  development:
    test.erb:
      target: /tmp/test.txt
      config:
        some_local_value: "This is the development environment"

  production:
    test.erb:
      target: /tmp/test.txt
      config:
        some_local_value: "This is the production environment"
```

Then running Tiller with `some_var="Hello from the environment"  tiller -b $PWD -n -v` results in this file:

```
$ cat /tmp/test.txt
Global value : This is available to all environments
Local value : This is the development environment
Something from the environment : Hello from the environment
```

And `some_var="Hello again from the environment"  tiller -b $PWD -n -v -e production` gets this:

```
$ cat /tmp/test.txt
Global value : This is available to all environments
Local value : This is the production environment
Something from the environment : Hello again from the environment
```
