### ISSUE TITLE
tiller with consul plugin enabled does not render templates to files.

### ISSUE THREAD

**Issue by pll** [markround/tiller#24]
When using tiller with the consul plugin enabled as a data_source only, templates are not being rendered to the target location on disk as expected.

Here is my output:
```
$ tiller -b . -v
tiller v0.7.9 (https://github.com/markround/tiller) <github@markround.com>
Using common.yaml v2 format configuration file
Using configuration from .
Using plugins from /usr/local/lib/tiller
Using environment test
Template sources loaded [FileTemplateSource]
Data sources loaded [EnvironmentDataSource, ConsulDataSource]
Available templates : ["foo.erb"]
Template generation completed
Executing ["true"]...
Child process forked with PID 28379.
Child process exited with status 0
Child process finished, Tiller is stopping.
```

Even running with `-d` I see consul being contacted to retrieve the KV pairs, which is successful. Once the KV retrieval is complete, I see this:

```
Available templates : ["foo.erb"]
#<ConsulDataSource:0x000000021282c8> : Connecting to Consul at http://127.0.0.1:8500
#<ConsulDataSource:0x000000021282c8> : Fetching template values from /tiller/values/test/foo.erb
#<ConsulDataSource:0x000000021282c8> : Fetching template values from /tiller/values/test/foo.erb
#<ConsulDataSource:0x000000021282c8> : Fetching template target values from /tiller/target_values/foo.erb/test
```

But my `common.yaml` specifies an on disk target:
```
---
exec: ["true"]
data_sources: [ "environment", "consul" ]
template_sources:  [ "file" ]
default_environment: 'test'

consul:
  url: "http://127.0.0.1:8500"
  register_services: false
  register_nodes: false
  values:
   global: '/globals'
   per_env: '/environments/%e'

environments:
  test:
    foo.erb:
      target : /tmp/tiller/foo.sh
      config:
        env: 'red'
```

eugenemayer1 verified that the code appears to be bailing out here:
`https://github.com/markround/tiller/blob/master/bin/tiller#L133`
