### ISSUE TITLE
Tiller does not produce when the only data source is Vault

### ISSUE THREAD

**Issue by liquid-sky** [markround/tiller#43]
Hi @markround,

I've noticed that with the configuration below, `tiller` does not produce parsed templates:

```yaml
data_sources: [ vault ]
template_sources: [ file ]

environments:
    production:
        postgres_dashboard.erb:
            target: 'parsed_template.txt'

vault:
 url: 'https://<MASTER_URL>'
 token: '<VAULT_TOKEN>'
```

```bash
➜  tiller  tiller -b . -v -n -e production
tiller v0.9.7 (https://github.com/markround/tiller) <github@markround.com>
Using configuration from .
Using plugins from /usr/local/lib/tiller


Using environment production
Template sources loaded [FileTemplateSource]
Data sources loaded [EnvironmentDataSource, VaultDataSource]
Available templates : ["postgres_dashboard.erb"]
Template generation completed
```

Although when data source is set to `data_sources: [ vault, file ]`,  it builds a template and saves to a file: 

```
Building template postgres_dashboard.erb
Not running as root, so not setting ownership/permissions on parsed_template.txt
```

It fails with `vault` as an only data source, because [target values variable is empty](https://github.com/markround/tiller/blob/master/bin/tiller#L170) and file generation is skipped.
