### ISSUE TITLE
Allow dynamics in the yaml files

### ISSUE THREAD

**Issue by DanielRedOak** [markround/tiller#47]
We have scenario we need to support where a field in a config file may need to come from a different source depending on the environment.  In this scenario development usually includes sane but not secret defaults that should be included.  For other environments the value of this field would need to be sourced from another service, Secret Server.  We have written a Ruby library that supports these lookups and returns values based on the `secret name` and `field name` that is requested.  Here is an example:

```
development:
  somefile.erb:
    config:
      somefield: 'sane default used by dev'

production:
  somefile.erb:
    config:
      somefield: ss_lookup('secret name', 'field')
```

If we could use dynamic info in the yaml files, this would open up the possibility to fulfill our need and allow other more complex use cases.  One thought of an implementation would be to allow erb style tags in the yaml that would be evaluated.

```
development:
  somefile.erb:
    config:
      somefield: 'sane default used by dev'

production:
  somefile.erb:
    config:
      somefield: <% ss_lookup('secret name', 'field') %>
```

I'm opening this ticket to start the conversation and hopefully collaborate on a workable solution.

Rightnow I think we'll be able to workaround this by running the resulting config files through as ERB files before producing the final output.
`Tiller -> Secret Server ERB Processor -> Final Output`
