### ISSUE TITLE
Dynamic values in top-level config blocks

### ISSUE THREAD

**Issue by markround** [markround/tiller#58]
Dynamic values are only currently processed inside datasources, they’re not being evaluated in the top-level or plugin configuration blocks. 

EG:

```yaml
exec: [ "/usr/bin/head /etc/haproxy/haproxy.cfg" ] # Testing
data_sources: [ defaults, file, 'zookeeper', environment ]
template_sources: [ file ]
md5sum: true
dynamic_values: true

zookeeper:
  uri: "<%= env_zkuri -%>"
  timeout: 5

environments:
  integration:
    haproxy.cfg.erb:
      target: /etc/haproxy/haproxy.cfg
```

Results in:

```
/home/akroenert/.gem/ruby/gems/tiller-1.1.0/lib/tiller/data/zookeeper.rb:25:in `rescue in setup': Could not connect to Zookeeper cluster : <%= env_zkuri -%> (RuntimeError)
    from /home/akroenert/.gem/ruby/gems/tiller-1.1.0/lib/tiller/data/zookeeper.rb:22:in `setup'
    from /home/akroenert/.gem/ruby/gems/tiller-1.1.0/lib/tiller/datasource.rb:9:in `initialize'
    from /home/akroenert/.gem/ruby/gems/tiller-1.1.0/bin/tiller:115:in `new'
    from /home/akroenert/.gem/ruby/gems/tiller-1.1.0/bin/tiller:115:in `block in <module:Tiller>'
    from /home/akroenert/.gem/ruby/gems/tiller-1.1.0/bin/tiller:110:in `each'
    from /home/akroenert/.gem/ruby/gems/tiller-1.1.0/bin/tiller:110:in `<module:Tiller>'
    from /home/akroenert/.gem/ruby/gems/tiller-1.1.0/bin/tiller:35:in `<top (required)>'
    from /home/akroenert/bin/tiller:22:in `load'
    from /home/akroenert/bin/tiller:22:in `<main>'
```
